# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.develop] # 'develop' is a branch name
  command = "echo 'develop'"
  base = "develop"
